supportedLLMs:
  - 'gpt-3.5-turbo'
  - 'gpt-4'
  - 'gpt-4-turbo'
  - 'claude-instant-1'
  - 'claude-2'
  - 'claude-instant-1.2'
  - 'claude-2.1'
  - 'claude-3-sonnet-20240229'
  - 'claude-3-opus-20240229'
  - 'claude-3-haiku-20240307'
supportedTestFrameworks:
  - 'None yet'
outputFile: '$HOME/.score/reports/output.html'
